### ISSUE TITLE
repuest to be added to a contributor to the project

### ISSUE THREAD

**Issue by bernhardeymann** [UniLuFS2020-ReplicationSeminar/CE2_Bernhard_Josia_Nico#1]
Hi guys, it seems i am not a contributor to the project yet. Pleas add me! Here's how to do it:

1. Navigate to Repository Settings:
Go to the repository on GitHub that you want to add contributors to.
Click on the "Settings" tab near the top-right corner of the repository page.
2. Access Collaborators & Teams:
In the left sidebar of the repository settings, click on "Collaborators & teams".
3. Add Collaborator:
In the "Collaborators" section, begin typing the GitHub username or email address of the person you want to add as a contributor.
GitHub will suggest matching users. Select the appropriate user from the suggestions.
Alternatively, you can invite contributors by email address if they don't have a GitHub account yet.
4. Set Collaborator Permissions:
Once you've added a collaborator, you can choose their permission level by clicking on the dropdown menu next to their name.
The available permission levels are:
Read: Allows read-only access to the repository.
Write: Allows read and write access to the repository, including the ability to push changes.
Admin: Allows full administrative access to the repository, including the ability to manage collaborators and settings.
Select the appropriate permission level for each collaborator.
5. Send Invitation (if applicable):
If you added a collaborator by email address and they don't have a GitHub account yet, GitHub will send them an invitation to join the repository as a collaborator. They'll need to accept the invitation and create a GitHub account to gain access.
6. Save Changes:
After adding collaborators and setting their permissions, click the "Save changes" button to confirm your changes.

**Comment by JDSchramm** [comment]
I added you. Its a bit weird, since i didnt add Nico but he was still a contributor, and he could pull and push the project.

**Comment by JDSchramm** [comment]
It should work now, try it

**Comment by bernhardeymann** [comment]
i saw the invitation and accepted it, still doesn't work. i'll check, if i find something on this issue

**Comment by bernhardeymann** [comment]
might have been an issue with my privacy settings. could you again send me an invite?

**Comment by bernhardeymann** [comment]
correction: it worked now. thanks!
